name: todo_list
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Use with the CupertinoIcons class for iOS style icons.
  get: ^4.6.6 #GetX Package for State management and Navigation
  device_preview: ^1.2.0 #For the Multiple Device Preview(MDP)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/app_logo.png
     - assets/images/introduction_one.png
     - assets/images/introduction_two.png
     - assets/images/introduction_three.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700